name: Continuous Integration
on: [push]
jobs:
  build_base:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_SHA >artifact.txt
      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: artifact.txt
