name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: env | sort
      - run: |
          echo ::set-env name=_CACHE_PATH::$RUNNER_WORKSPACE/mycache
          echo ::set-env name=_CACHE_TYPE::cache-RUNNER_WORKSPACE
          echo ::set-env name=_CACHE_TAG::2

      - uses: actions/cache@v1
        with:
          path: ${{ env._CACHE_PATH }}
          key: ${{ env._CACHE_TYPE }}-${{ env._CACHE_TAG }}
          restore-keys: |
            ${{ env._CACHE_TYPE }}-

      - run: find $_CACHE_PATH || true

      - run: |
          mkdir -p $_CACHE_PATH
          echo foo >$_CACHE_PATH/myfile
