name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    steps:
      - run: env | sort
      - run: |
          echo ::set-env name=_CACHE_PATH::/mycache
          echo ::set-env name=_CACHE_TYPE::cache-root
          echo ::set-env name=_CACHE_TAG::a b c d

      - run: |
          echo $_CACHE_TAG

      - run: cat /github/workflow/event.json
