name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    strategy:
      matrix:
        modules:
          - [ {a: 1}, b, c ]
          - [ a, {c: [1,2,3]} ]
    steps:
      - env:
          MATRIX: ${{ toJSON(matrix) }}
        run: |
          set -x
          env
          echo $MATRIX
