name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    strategy:
      matrix:
        foo:
          - { a: [1, 2, 3] }
          - { a: [1, 3] }
          - { b: [2, 3] }
    steps:
      - run: env | sort
