name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: alpine
      options: --privileged
    steps:
      - run: env | sort
      - run: |
          mkdir -p /home/runner/work/_temp
          mount --bind $RUNNER_TEMP /home/runner/work/_temp
          ls /home/runner/work/_temp
