name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    strategy:
      matrix:
        modules:
          - [ casper ]
          - [] # rest
    steps:
      - run: env | sort
      - run: echo '${{ toJSON(matrix.modules) }}'
      - run: find /
