name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: alpine
    strategy:
      matrix:
        foo:
          - 1
          - 2
          - 3
    steps:
      - run: env | sort
