name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rchain/buildenv:latest
    steps:
      - run: env | sort
      - run: env | sort
        env:
          SBT_OPTS: "$SBT_OPTS sbt.ci"
