name: Continuous Integration
on: [push, pull_request]

jobs:
  build_base:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ secrets.FOO }}
    steps:
      - run: |
          echo "The secret is '$FOO'."
