name: Continuous Integration
on: [push, pull_request]

jobs:
  show_env:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort

  access_secrets:
    runs-on: ubuntu-latest
    env:
      SECRET_FOO: ${{ secrets.SECRET_FOO }}
    steps:
      - run: echo "The secret is '$(echo $SECRET_FOO | sed $'s/./&\u200b/g')'."
