name: Continuous Integration
on: [push]
jobs:
  build_base:
    runs-on: ubuntu-latest
    steps:
      - run: true

  test_a:
    runs-on: ubuntu-latest
    needs: build_base
    steps:
      - run: false

  test_b:
    runs-on: ubuntu-latest
    needs: build_base
    steps:
      - run: true

  finish_join:
    runs-on: ubuntu-latest
    needs:
      - test_a
      - test_b
    steps:
      - run: true

  finish_success:
    name: bors_finish_check
    if: success()
    runs-on: ubuntu-latest
    needs: finish_join
    steps:
      - name: Mark the job as successful
        run: exit 0

  finish_failure:
    name: bors_finish_check
    if: "!success()"
    runs-on: ubuntu-latest
    needs: finish_join
    steps:
      - name: Mark the job as a failure
        run: exit 1
