name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: woky/rchain-buildenv
    strategy:
      matrix:
        modules:
          - [ casper ]
          - [] # rest
    steps:
      - run: env | sort
      - run: echo '${{ toJSON(matrix.modules) }}' | jq .
      - run: find /
      - run: ./.github/yaml2json .github/workflows/test.yml | jq .
