name: Continuous Integration
on: [push]
jobs:
  cache_in_github_workspace:
    runs-on: ubuntu-latest
    container: woky/rchain-buildenv
    strategy:
      matrix:
        modules:
          - [ casper ]
          - [] # rest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v1
      - run: env | sort
      - run: ./.github/yaml2json <.github/workflows/test.yml | jq .
