name: Continuous Integration
on: [push]
jobs:
  build_base:
    runs-on: ubuntu-latest
    steps:
      - run: echo foo >artifact.txt
      - uses: actions/upload-artifact@v1
        with:
          name: artifact-${{ env.GITHUB_SHA }}
          path: artifact.txt
